Repository scp756-221/term-project-hummingbird, pull requests merged in 2022-03, with the labels that each got.

#23 config for initialize playlist image
  s3/Dockerfile
  s3/Makefile
  s3/README.md
  s3/app.py
  s3/builda1.sh
  s3/music.csv
  s3/odd/music.csv
  s3/runa1.sh
  s3/unique_code.py
Labels: enhancement

#25 fix s3 makefile bug
  s3/Makefile
Labels: bug

#30 Create playlist
  mcli/Makefile
  s3/app.py
Labels: bug, enhancement

#33 Kunma
  .DS_Store
  gatling/.DS_Store
  gatling/simulations/.DS_Store
  mcli/Dockerfile
  mcli/Makefile
  mcli/mcli.py
Labels: enhancement
